### ISSUE TITLE
persistent URLs for Issues

### ISSUE THREAD

**Issue by ebenenglish** [marriott-library/newspaper_works#120]
*This is a placeholder ticket*

Issues should have persistent URLs that are human-readable-ish and conform to a semantic hierarchical pattern.

See Chronicling America [link documentation](https://chroniclingamerica.loc.gov/about/api/#link).

**Comment by brianmcbride** [comment]
**Descriptive Summary**
We want to provide end users and more advanced users the ability to systemically crawl through newspaper issues using a standard newspaper semantic hierarchal pattern. Adding type of functionality by providing persistent URLs will provide users with a means to easy locate a specific newspaper/issue and will provide developers a predictable way to crawl the site while providing the basic functionality to enable IoT WoT devices to engage with the sites. 

**Proposed Structure**
(based on existing models in development documentation) @ebenenglish @seanupton @JacobR 
https://host/newspapers/[NewspaperTitle]/[NewspaperIssueTitle]/

**Rationale**
This functionality will provide the necessary support to enable for users to engage with the site in many ways, which include:
- A semantic hierarchy will make navigating newspaper issues more predictable
- Enable easier crawling of site by search engines, which may help improve SEO profile
- Provide developers an easy way to predictably crawl the site
- Enable basic support for IoT WoT devices to engage with site
- Allow users to more easily reference/cite newspaper issues 

**Expected behavior**
As a user I will be able to do the following:
 - In a web browser be able to view newspaper view all newspaper issues belonging to a newspaper
  - Example: `https://host/newspapers/SaltLakeTribune/NewspaperIssueTitle` will display the specific Salt Lake Tribune Issue 


**This ticket will be complete when:**
Functionality described above is implemented.

**Comment by ebenenglish** [comment]
Couple of things to think about here...

1. Using the actual text title of the newspaper title (vs. the LCCN) has advantages and disadvantages
  * Advantages:
    * URLs have more semantic info, so they're easier to remember
    * may be more SEO friendly
  * Disadvantages
    * Titles may change over time
    * Titles may have characters that are non-URL compatible
    * Matching titles to identifiers requires either (A) a lookup db table (increases app complexity) or (B) a keyword search of the Solr index on the title (this could be fuzzy)

There are also disadvantages to using the LCCN:
  * URLs impossible to remember
  * likely less SEO friendly
  * some newspapers (particularly student newspapers) may not have an LCCN?


2. Issues are unlikely to have descriptive titles (`NewspaperIssueTitle`), so it seems like simply using the date will have to suffice

3. There may be more than one edition for a date. If we are supporting multiple editions per date, we'll need to include that in the URL structure, similar to how Chron Am does this (`/lccn/sn86069873/1900-01-05/ed-1/`)

I wonder if we should bounce this off of some folks from the Newspapers AC or IG?

**Comment by kestlund** [comment]
I am very used to so I really like the LCCNs from using the APIs for Chronicling America.  They definitely are more for a machine-readable API than easy to remember, though, as pointed out.  

LCCNs are not limited to newspapers and avoid many of the title issues that are so repetitive, as well as changing.  
Literary magazine: https://oregonnews.uoregon.edu/lccn/2012260365/
Student newspaper: http://panewsarchive.psu.edu/lccn/sn85054904/

The international newspaper is an interesting issue that immediately came to mind, as well. Many international newspapers in CRL or held by major US research libraries would have LCCNs, but that is certainly a limited set.  (CRL, I think, has one of the best handles on unique number and title problems with newspapers globally that they may be willing to share.) 

Europeana also uses a bib control number in their URLs. http://www.europeana.eu/portal/en/record/9200300/BibliographicResource_3000051805495.html

I would suggest making the persistent URL based on LCCN or another control number.  You could adopt the LC API scheme, and when an lccn is not available, you could use that control prefix code in the URL for lccn. This would not eliminate the ability to also have a more user friendly / SEO friendly URL, as well.

**Comment by seanupton** [comment]
Re: pubs without LCCN... I wonder if `.identifier` of `NewspaperTitle` should be both:

* a settable field (for `dcterms:identifier`), which is local identifier or non-LCCN control number,
* and an accessor method that falls back to `.lccn` value when nothing else is set (which would be most of the time)?

_For publications with LCCN, the LCCN would always be the identifier, and the `.identifier` field could be the accessor / abstraction for the URL routing?  I'm not sure what else folks are using for identifier of a publication, but NewspaperWorks does not have its own local identifiers to conflict with this distinct from minted object id, which has its own accessor?_

**Comment by ebenenglish** [comment]
It probably wouldn't be too much extra work to make this configurable and/or customizable. The implementation could customize which field they want to use for this in config/initializers/hyrax.rb or something like that. It would default to `.lccn`.

No matter what field is used, the controller will have to do a lookup in Solr for the NewspaperTitle id that matches the LCCN (or other unique id), so it's easy enough to have the controller use a field name from the application config to construct the search.

The simplest way to implement this feature will be for the controller to parse the incoming params, lookup data from Solr, and then redirect the request to the appropriate controller. However, this means the user's browser won't show the `/lccn/sn86069873/1900-01-05/ed-1/` style URL once the page is loaded, but rather `/concern/newspaper_issues/a1b2c3d`. That page would _display_ the 'permalink' URL somewhere in the metadata, I suppose.

If we pursue the approach above, it probably means the SEO of the identifier is basically inconsequential, since no crawler will ever 'see' it when crawling the site. That kind of throws the title-as-identifier option out the window.

**Comment by ebenenglish** [comment]
Fixed via #141.

There is now a configuration option which can be set in `config/initializers/newspaper_works.rb` that allows the implementation to customize:

* `publication_unique_id_property` (defaults to `:lccn`)
* `publication_unique_id_field` (defaults to `lccn_tesim`)

These allow the persistent URLs to use a different unique semantic identifier for the `NewspaperTitle` object at the top of the link hierarchy.
