### ISSUE TITLE
persistent URLs for Pages

### ISSUE THREAD

**Issue by ebenenglish** [marriott-library/newspaper_works#121]
*This is a placeholder ticket*

Pages should have persistent URLs that are human-readable-ish and conform to a semantic hierarchical pattern.

See Chronicling America [link documentation](https://chroniclingamerica.loc.gov/about/api/#link).

**Comment by brianmcbride** [comment]
**Descriptive Summary**
We want to provide end users and more advanced users the ability to systemically crawl through newspaper issues using a standard newspaper semantic hierarchal pattern. Adding type of functionality by providing persistent URLs will provide users with a means to easy locate a specific newspaper/issue and will provide developers a predictable way to crawl the site while providing the basic functionality to enable IoT WoT devices to engage with the sites. 

**Proposed Structure**
(based on existing models in development documentation) @ebenenglish @seanupton @JacobR 
https://host/newspapers/[NewspaperTitle]/[NewspaperIssueTitle]/[PageLabel]/

**Rationale**
This functionality will provide the necessary support to enable for users to engage with the site in many ways, which include:
- A semantic hierarchy will make navigating newspaper pages more predictable
- Enable easier crawling of site by search engines, which may help improve SEO profile
- Provide developers an easy way to predictably crawl the site
- Enable basic support for IoT WoT devices to engage with site
- Allow users to more easily reference/cite newspaper pages

**Expected behavior**
As a user I will be able to do the following:
 - In a web browser I can enter in, a mostly predictable, URL that will bring me to a specific newspaper issue page 
    - Example: `https://host/newspapers/SaltLakeTribune/NewspaperIssueTitle/PageLabel` will display the specific Salt Lake Tribune page 
- Share the URL persistent URL 

**This ticket will be complete when:**
Functionality described above is implemented.

**Comment by ebenenglish** [comment]
Fixed via #141.
