### ISSUE TITLE
Text and coordinate extraction from ingested NewspaperPage image

### ISSUE THREAD

**Issue by seanupton** [marriott-library/newspaper_works#26]
Extract and persist, via tesseract, the following derivatives from page images (using hOCR coordinate data as source):

1. ALTO 2.1 (XML file)
2. Plain text for full-text search (TXT file)
3. IIIF Annotation List (JSON file)

This extraction should happen for both uploaded (through browser) TIFF images for a NewspaperPage and for pages which have image file data added via `NewspaperWorks::Ingest::NewspaperPageIngest`.

## references and links:

* This is what Princeton's Plum does with tesseract:  https://github.com/pulibrary/plum/blob/master/app/services/processors/ocr.rb#L6
* https://github.com/filak/hOCR-to-ALTO
* https://www.loc.gov/ndnp/guidelines/archive/OCRSpecs-1-17.pdf
* ALTO to Annotation List: https://github.com/glenrobson/iiif_stuff/tree/master/alto2annotations

**Comment by ebenenglish** [comment]
Note that "IIIF Annotation List (JSON file)" has been removed as a stored derivative, due to the preponderance of URIs (which reference a separate IIIF manifest) that need to be included in the data structure, which are difficult to code in a way that would allow institutions to customize the URIs.

Instead, we will create a new ticket for a more simply-structured word-coordinate JSON file to be stored as a derivative. This file will then serve as the source data for outputting coordinate data as needed by client applications, as a full IIIF Anno List or other formats as needed.
