### ISSUE TITLE
Relationship query methods for models, with tests

### ISSUE THREAD

**Issue by seanupton** [marriott-library/newspaper_works#5]
Relationship methods should be defined for each model, for querying both parent-to-child (filtered members) and child-to-parent (filtered member_of) relationships.  Some relationships have a necessarily singular target, and should return an object, while others should return an array of filtered objects selected from query methods provided by the framework.

Query Methods
----------------

- `NewspaperTitle.issues` — *returns Array of 0..* `NewspaperIssue` objects*
- `NewspaperTitle.containers` — *returns Array of 0..* `NewspaperContainer` objects*
- `NewspaperIssue.publication` — *returns single `NewspaperTitle` object or nil`
- `NewspaperIssue.articles` — *returns Array of 0..* `NewspaperArticle` objects`
- `NewspaperIssue.pages` — *returns Array of 0..* `NewspaperPage` objects`
- `NewspaperContainer.publication` — *returns single `NewspaperTitle` object or nil`
- `NewspaperContainer.pages` — *returns Array of 0..* `NewspaperPage` objects`
- `NewspaperPage.articles` — *returns Array of 0..* `NewspaperArticle` objects`
- `NewspaperPage.issue` — *returns singular `NewspaperIssue` object or nil`
- `NewspaperPage.containers` — *returns Array of 0..* `NewspaperContainer` objects`
- `NewspaperPage.publication` — *returns single `NewspaperTitle` object or nil`
  - **Transitive** via, in order: `NewspaperPage.issue.publication`, `NewspaperPage.containers[0].publication`
- `NewspaperArticle.pages` — *returns Array of 0..* `NewspaperPage` objects`
- `NewspaperArticle.issue` — *returns singular `NewspaperIssue` object or nil`
- `NewspaperArticle.publication` — *returns single `NewspaperTitle` object or nil`
  - **Transitive** via, in order: `NewspaperArticle.issue.publication`, `NewspaperPage.issue.publication`, `NewspaperPage.containers[0].publication`
- `NewspaperArticle.containers` — *returns Array of 0..* `NewspaperContainer` objects`
  - **Transitive** via `NewspaperArticle.pages[0].containers`

Tests
-----

*Should include RSpec tests for:*

- Any aggregation helper classes or methods.
- Each method tested on RSpec tests for each respective model class.

**Comment by seanupton** [comment]
A few quick notes:
1. We can assume that a page could have more than one container, only because it is possible that we have multiple scans of the same page (e.g. from different vendors)?
2. By proxy of #1, there may be some difficulty querying a transitive relationship from a  `NewspaperArticle` to 0..* `NewspaperContainer`objects because we might need to handle scope where an article is on more than one page (perhaps split across reels or sections)?
3. No downward transitive relationship from `NewspaperTitle` to articles or pages should exist.  Having anything like seems to be bordering on collection territory, and I suspect what should happen is some kind of 1:1 between a `NewspaperTitle` work and an associated collection-per-title?

**Comment by ebenenglish** [comment]
Responding to @seanupton 

1. In the PCDM Profile we stated `A NewspaperPage MAY be a member of one and only one NewspaperContainer object.` Having multiple scans of the same page seems very unlikely.

2. Given `#1` above, theoretically the transitive relationship from `NewspaperArticle` to `NewspaperContainer` should be possible. However, if this creates a lot of work, I'm tempted not to worry about `Container<->Article` relationships, since I'm not sure we'll need them. 

3. I'm OK with no direct `Title->Article` or `Title->Page` relationships. The relationship between Hyrax "Collections" and `NewspaperTitle` objects will depend on the implementation, I think. Some institutions may want a single "Historic Newspapers" collection, while others may want a collection-per-title approach.

**Comment by seanupton** [comment]
Implemented in newsapp_experiments
